### ISSUE TITLE
How can i log headers, request, response content using the plugin

### ISSUE THREAD

**Issue by abrahamgolla** [Optum/kong-splunk-log#10]

**Comment by jeremyjpj0916** [comment]
This plugin is only intended to log the meta data of API transactions(as storing large amounts of data in splunk can add additional costs). I would check alternative plugins and fork this plugins logic if you need more details:
ex: https://docs.konghq.com/hub/kong-inc/http-log/ shows how to log extra headers. I don't know of any plugins actually logging the body(request/response) currently but you can find old pull requests to Kong that show how to do that.
