### ISSUE TITLE
Configuring the plugin at the service level causes unexpected behavior

### ISSUE THREAD

**Issue by codereflection** [Optum/kong-splunk-log#5]
https://github.com/Optum/kong-splunk-log/blob/f0e7a17948919b536c0bf79838feda5afbc22956/src/handler.lua#L48-L50

I am having trouble with this plugin while configuring it at the Service level, rather than the Route or Global level.  I believe it is related to this part of the code.

When I configure the plugin at two different services, I am seeing traffic from one service getting logged to the incorrect Splunk token.

**Scenario 1:**

Workspace | Service | Splunk Token | Plugin State
----------- | ----------- | ----------- | -----------
Default | health-check | A | Enabled
DEV | test | B | Enabled

_Resulting behavior_: Splunk token `A` receives `health-check` traffic logs _and_ `test` traffic logs.  Splunk token `B` does not receive any of the logs at all.

**Scenario 2:**

Workspace | Service | Splunk Token | Plugin State
----------- | ----------- | ----------- | -----------
Default | health-check | A | Disabled
DEV | test | B | Enabled

_Resulting behavior_: Splunk token `B` receives `health-check` traffic logs _and_ `test` traffic logs, even though the plugin for `health-check` is disabled, traffic for this service is still being logged and ending up at this Splunk index.

**Testing other plugins and Kong support**

I've open up a ticket with Kong and they did some internal investigation. They were able to duplicate the issue with this plugin, and verify that the behavior does not happen with other plugins.  They pointed out lines of code mentioned above as a possible reason for this unexpected behavior.

**Possible workaround?**

It seems like the possible workaround for this is to log all traffic globally to a single Splunk token, or to apply the plugin only at the route level.  What we would prefer is to be able to use the plugin at the service level, or possibly also at the consumer level.

**Comment by jeremyjpj0916** [comment]
@codereflection 

We use this plugin globally personally. If you want service level optimization have you tried a fork of the plugin and do this in code?:
```
 local service_id = conf.service_id or "global" 
  
 local buf = buffers[service_id] 
```

And see if that works. 

The code of this plugin was originally taken from an older iteration of Kong's HTTP Log plugin and reworked for Splunk integration. So makes sense Kong should be fully familiar with this implementation.

I run a pretty big bucket size of messages(20-50 generally) and have had decent performance that way but still do see cases where the TPS gets too high and Kong's logging starts to fall behind from real time. I documented a more modern testing of that over here too with some of Kong's latest code base:
https://github.com/Kong/kong/issues/5164

**Comment by codereflection** [comment]
Thank you @jeremyjpj0916 .  I will test out a fork using your suggested change.  We're probably going to use the plugin globally as well, given that it's less configuration.

**Comment by jeremyjpj0916** [comment]
@codereflection Perfect, sounds like you have next steps. I don't think at this time we will be looking to update this codebase ourselves on the service id venture, but if you do it in a way that can produce a non-breaking change we would be happy to review the PR and merge it down the road. Likely the next refactor of this codebase for us will be to take the more modern Kong HTTP Log plugin logic once I feel they have resolved the issue of real time logs falling behind under higher tps levels as a global plugin.

**Comment by codereflection** [comment]
@jeremyjpj0916 that makes sense.  Thanks for the quick responses on this.
